config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [ :index, :show, :new, :create  ] do
    resources :doses, only: [ :new , :create]
  end
  resources :doses, only: [:destroy]

  root "cocktails#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :ingredient, uniqueness: { scope: :cocktail }
  validates :ingredient_id, presence: true
  validates :cocktail_id, presence: true
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show

  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(params_dose)
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  protected

  def params_dose
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name, placeholder: "Mojito" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<h1 class="text-center">Your cocktail menu</h1>

<div class="text-center padded">
  <%= link_to "Create a cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card text-center">
          <h2><%= cocktail.name %></h2>
          <%= cl_image_tag cocktail.photo, width: 100, height: 150, crop: :fit %>
          <%= link_to cocktail.name, cocktail_path(cocktail), class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= render 'form' %>

<%= link_to 'Back to home', cocktails_path %>

app/views/cocktails/show.html.erb
<div class="show-header">
  <h2><%= @cocktail.name %></h2>
  <%= cl_image_tag(@cocktail.photo, width: 400, height: 300, crop: :thumb, gravity: :face, :effect => "pixelate_faces") %>

  <div class="right-side">
    <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail.id), {class: "btn btn-primary" } %>
    <%= link_to "Back", cocktails_path, {class: "btn btn-primary" } %>
    <%= link_to "Add Photo", new_cocktail_dose_path(@cocktail.id), {class: "btn btn-primary" } %>
  </div>
</div>

<table class="table table-striped">
  <tr>
    <td><strong>Ingredients</strong></td>
    <td><strong>Description</strong></td>
    <td></td>
  </tr>
  <% @cocktail.doses.each do |i| %>
    <tr>
      <td><%= Ingredient.find(i.ingredient_id).name %></td>
      <td><%= i.description %></td>
      <td><%= link_to "Delete Ingredient", dose_path(i), method: :delete, confirm: "Are you sure?", class: "btn btn-success" %></td>
    </tr>
  <% end %>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :cocktail_id, as: :hidden, input_html: { value: @cocktail.id } %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Submit", class: "btn btn-success" %>
<% end -%>

app/views/doses/new.html.erb
<% content_for(:title) do %>
  "New Ingredient"
<% end -%>
<h2>Add Ingredient</h2>
<%= render 'form' %>

<%= link_to 'Back to Cocktail', cocktail_path(@cocktail) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>